//! SQL Parser — partial port of `sqlite-source/src/parse.y`.
//!
//! The C source's parser is generated by Lemon (an LALR(1) parser
//! generator) and produces a state machine. For the T-0015 slim
//! scope, we implement a recursive-descent parser for a small SQL
//! subset:
//! - `SELECT [* | col [, col]*] FROM table [WHERE cond]`
//! - `INSERT INTO table VALUES (val [, val]*)`
//! - `CREATE TABLE table (col TYPE [, col TYPE]*)`
//! - `DROP TABLE table`
//!
//! # C source correspondence
//!
//! | Rust item       | C source                          |
//! |-----------------|-----------------------------------|
//! | `Parser::new`   | `sqlite3ParserAlloc` (lemon)      |
//! | `Parser::parse` | `sqlite3Parser` (parse.c, generated)|
//!
//! # Scope (T-0015)
//!
//! The recursive-descent approach gives a working parse tree for
//! common queries but is not as general as Lemon's LALR(1) parser.
//! A full port would re-implement Lemon in Rust (significant scope);
//! for now this minimal version covers the most common statements
//! and is sufficient for testing the upstream Tokenizer integration.

use crate::error::SqliteError;
use crate::tokenize::{Keyword, Punct, Token, TokenKind};

/// A parsed SQL statement (AST root).
#[derive(Debug, Clone, PartialEq)]
pub enum Stmt {
    /// `SELECT ...`
    Select(SelectStmt),
    /// `INSERT INTO ... VALUES (...)`
    Insert(InsertStmt),
    /// `CREATE TABLE ...`
    CreateTable(CreateTableStmt),
    /// `DROP TABLE ...`
    DropTable(DropTableStmt),
    /// Empty statement (just `;`).
    Empty,
}

/// `SELECT [* | col [, col]*] FROM table [WHERE cond]`
#[derive(Debug, Clone, PartialEq)]
pub struct SelectStmt {
    /// `true` for `SELECT *`, `false` for column list.
    pub all: bool,
    /// Columns to select (empty if `all` is true).
    pub columns: Vec<String>,
    /// The table to select from.
    pub from: String,
    /// Optional WHERE clause. Slim subset: comparison + AND/OR combinations.
    pub where_clause: Option<WhereExpr>,
}

/// Comparison operator in a WHERE clause.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum WhereOp {
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
}

/// A simple WHERE expression: a single `col op literal` comparison, or
/// a boolean combination (AND/OR) of two sub-expressions.
#[derive(Debug, Clone, PartialEq)]
pub enum WhereExpr {
    /// `column op value` — slim subset supports integer/real/string/null RHS.
    Cmp {
        op: WhereOp,
        column: String,
        value: Value,
    },
    /// `a AND b`
    And(Box<WhereExpr>, Box<WhereExpr>),
    /// `a OR b`
    Or(Box<WhereExpr>, Box<WhereExpr>),
}

/// `INSERT INTO table VALUES (val [, val]*)`
#[derive(Debug, Clone, PartialEq)]
pub struct InsertStmt {
    pub table: String,
    pub values: Vec<Value>,
}

/// `CREATE TABLE table (col TYPE [, col TYPE]*)`
#[derive(Debug, Clone, PartialEq)]
pub struct CreateTableStmt {
    pub table: String,
    pub columns: Vec<ColumnDef>,
}

/// A column definition in CREATE TABLE.
#[derive(Debug, Clone, PartialEq)]
pub struct ColumnDef {
    pub name: String,
    /// Type name (e.g. "INTEGER", "TEXT", "REAL"). Lowercased.
    pub type_name: String,
}

/// `DROP TABLE table`
#[derive(Debug, Clone, PartialEq)]
pub struct DropTableStmt {
    pub table: String,
}

/// A literal value in SQL.
#[derive(Debug, Clone, PartialEq)]
pub enum Value {
    Integer(i64),
    Real(f64),
    String(String),
    Null,
    /// Bare identifier (column name reference).
    Identifier(String),
}

/// The SQL Parser.
pub struct Parser<'a> {
    tokens: &'a [Token],
    pos: usize,
}

impl<'a> Parser<'a> {
    /// Construct a new parser over the given token stream.
    pub fn new(tokens: &'a [Token]) -> Self {
        Parser { tokens, pos: 0 }
    }

    /// Parse a sequence of statements. Returns an error on the first
    /// parse failure.
    pub fn parse(&mut self) -> Result<Vec<Stmt>, SqliteError> {
        let mut stmts = Vec::new();
        loop {
            self.skip_optional_semi();
            if self.pos >= self.tokens.len() {
                break;
            }
            let stmt = self.parse_one_stmt()?;
            stmts.push(stmt);
            // Optional trailing semicolon.
            self.skip_optional_semi();
        }
        Ok(stmts)
    }

    /// Parse a single statement.
    fn parse_one_stmt(&mut self) -> Result<Stmt, SqliteError> {
        let kw = match self.peek().kind {
            TokenKind::Keyword(k) => k,
            _ => return Err(SqliteError(1)),
        };
        match kw {
            Keyword::Select => Ok(Stmt::Select(self.parse_select()?)),
            Keyword::Insert => Ok(Stmt::Insert(self.parse_insert()?)),
            Keyword::Create => Ok(Stmt::CreateTable(self.parse_create_table()?)),
            Keyword::Drop => Ok(Stmt::DropTable(self.parse_drop_table()?)),
            _ => Err(SqliteError(1)),
        }
    }

    fn parse_select(&mut self) -> Result<SelectStmt, SqliteError> {
        self.expect_keyword(Keyword::Select)?;
        let mut all = false;
        let mut columns = Vec::new();
        if self.is_punct(Punct::Star) {
            self.advance();
            all = true;
        } else {
            loop {
                columns.push(self.parse_identifier()?);
                if self.is_punct(Punct::Comma) {
                    self.advance();
                } else {
                    break;
                }
            }
        }
        self.expect_keyword(Keyword::From)?;
        let from = self.parse_identifier()?;
        let where_clause = if self.is_keyword(Keyword::Where) {
            self.advance();
            Some(self.parse_where_expr()?)
        } else {
            None
        };
        Ok(SelectStmt {
            all,
            columns,
            from,
            where_clause,
        })
    }

    /// Parse a WHERE expression: `cmp (AND cmp)* (OR cmp (AND cmp)*)*`
    /// with left-to-right evaluation (slim subset — no precedence climbing).
    fn parse_where_expr(&mut self) -> Result<WhereExpr, SqliteError> {
        let mut left = self.parse_where_and()?;
        while self.is_keyword(Keyword::Or) {
            self.advance();
            let right = self.parse_where_and()?;
            left = WhereExpr::Or(Box::new(left), Box::new(right));
        }
        Ok(left)
    }

    fn parse_where_and(&mut self) -> Result<WhereExpr, SqliteError> {
        let mut left = self.parse_where_cmp()?;
        while self.is_keyword(Keyword::And) {
            self.advance();
            let right = self.parse_where_cmp()?;
            left = WhereExpr::And(Box::new(left), Box::new(right));
        }
        Ok(left)
    }

    fn parse_where_cmp(&mut self) -> Result<WhereExpr, SqliteError> {
        let column = self.parse_identifier()?;
        let op = self.parse_where_op()?;
        let value = self.parse_value()?;
        Ok(WhereExpr::Cmp { op, column, value })
    }

    fn parse_where_op(&mut self) -> Result<WhereOp, SqliteError> {
        let op = match self.peek().kind {
            TokenKind::Punct(Punct::Eq) => WhereOp::Eq,
            TokenKind::Punct(Punct::Ne) => WhereOp::Ne,
            TokenKind::Punct(Punct::Lt) => WhereOp::Lt,
            TokenKind::Punct(Punct::Le) => WhereOp::Le,
            TokenKind::Punct(Punct::Gt) => WhereOp::Gt,
            TokenKind::Punct(Punct::Ge) => WhereOp::Ge,
            _ => return Err(SqliteError(1)),
        };
        self.advance();
        Ok(op)
    }

    fn parse_insert(&mut self) -> Result<InsertStmt, SqliteError> {
        self.expect_keyword(Keyword::Insert)?;
        self.expect_keyword(Keyword::Into)?;
        let table = self.parse_identifier()?;
        self.expect_keyword(Keyword::Values)?;
        self.expect_punct(Punct::LParen)?;
        let mut values = Vec::new();
        loop {
            values.push(self.parse_value()?);
            if self.is_punct(Punct::Comma) {
                self.advance();
            } else {
                break;
            }
        }
        self.expect_punct(Punct::RParen)?;
        Ok(InsertStmt { table, values })
    }

    fn parse_create_table(&mut self) -> Result<CreateTableStmt, SqliteError> {
        self.expect_keyword(Keyword::Create)?;
        self.expect_keyword(Keyword::Table)?;
        let table = self.parse_identifier()?;
        self.expect_punct(Punct::LParen)?;
        let mut columns = Vec::new();
        loop {
            let name = self.parse_identifier()?;
            let type_name = if self.is_id_or_keyword() {
                self.parse_identifier()?
            } else {
                String::new()
            };
            columns.push(ColumnDef { name, type_name: type_name.to_uppercase() });
            if self.is_punct(Punct::Comma) {
                self.advance();
            } else {
                break;
            }
        }
        self.expect_punct(Punct::RParen)?;
        Ok(CreateTableStmt { table, columns })
    }

    fn parse_drop_table(&mut self) -> Result<DropTableStmt, SqliteError> {
        self.expect_keyword(Keyword::Drop)?;
        self.expect_keyword(Keyword::Table)?;
        let table = self.parse_identifier()?;
        Ok(DropTableStmt { table })
    }

    fn parse_identifier(&mut self) -> Result<String, SqliteError> {
        let tok = self.peek();
        if let TokenKind::Id = tok.kind {
            let s = tok.text.clone();
            self.advance();
            Ok(s)
        } else {
            Err(SqliteError(1))
        }
    }

    fn parse_value(&mut self) -> Result<Value, SqliteError> {
        let tok = self.peek();
        match &tok.kind {
            TokenKind::Integer => {
                let s = tok.text.clone();
                let v: i64 = s.parse().map_err(|_| SqliteError(1))?;
                self.advance();
                Ok(Value::Integer(v))
            }
            TokenKind::Float => {
                let s = tok.text.clone();
                let v: f64 = s.parse().map_err(|_| SqliteError(1))?;
                self.advance();
                Ok(Value::Real(v))
            }
            TokenKind::String => {
                let s = tok.text.clone();
                self.advance();
                Ok(Value::String(s))
            }
            TokenKind::Keyword(Keyword::Null) => {
                self.advance();
                Ok(Value::Null)
            }
            TokenKind::Id => {
                let s = tok.text.clone();
                self.advance();
                Ok(Value::Identifier(s))
            }
            _ => Err(SqliteError(1)),
        }
    }

    fn expect_keyword(&mut self, kw: Keyword) -> Result<(), SqliteError> {
        if self.is_keyword(kw) {
            self.advance();
            Ok(())
        } else {
            Err(SqliteError(1))
        }
    }

    fn expect_punct(&mut self, p: Punct) -> Result<(), SqliteError> {
        if self.is_punct(p) {
            self.advance();
            Ok(())
        } else {
            Err(SqliteError(1))
        }
    }

    fn is_keyword(&self, kw: Keyword) -> bool {
        matches!(self.peek().kind, TokenKind::Keyword(k) if k == kw)
    }

    fn is_punct(&self, p: Punct) -> bool {
        matches!(self.peek().kind, TokenKind::Punct(p2) if p2 == p)
    }

    fn is_id_or_keyword(&self) -> bool {
        matches!(
            self.peek().kind,
            TokenKind::Id | TokenKind::Keyword(_)
        )
    }

    fn skip_optional_semi(&mut self) {
        while self.is_punct(Punct::Semi) {
            self.advance();
        }
    }

    fn peek(&self) -> &Token {
        // The parser must not call peek() past the end. But to be
        // safe, return a synthetic EOF token. We can't construct
        // a TokenKind::Eof without text, so we use a "match
        // against the pattern" approach: callers should check
        // `pos < tokens.len()` first.
        if self.pos >= self.tokens.len() {
            // SAFETY: this is a fallback for the EOF case. The
            // token has kind=Keyword(NotKeyword) and empty text
            // so no match_keyword/expect_*-method will accept it.
            static EOF: Token = Token {
                kind: TokenKind::Keyword(Keyword::NotKeyword),
                text: String::new(),
                line: 0,
                col: 0,
            };
            &EOF
        } else {
            &self.tokens[self.pos]
        }
    }

    fn advance(&mut self) {
        if self.pos < self.tokens.len() {
            self.pos += 1;
        }
    }
}

/// Convenience: tokenize and parse an SQL string.
pub fn parse_sql(sql: &str) -> Result<Vec<Stmt>, SqliteError> {
    let tokens = crate::tokenize::tokenize(sql)?;
    let mut parser = Parser::new(&tokens);
    parser.parse()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(sql: &str) -> Vec<Stmt> {
        parse_sql(sql).unwrap()
    }

    #[test]
    fn empty() {
        assert_eq!(parse(""), vec![]);
        assert_eq!(parse(";"), vec![]);
    }

    #[test]
    fn select_star() {
        let stmts = parse("SELECT * FROM t");
        assert_eq!(stmts.len(), 1);
        match &stmts[0] {
            Stmt::Select(s) => {
                assert!(s.all);
                assert!(s.columns.is_empty());
                assert_eq!(s.from, "t");
                assert!(s.where_clause.is_none());
            }
            _ => panic!("expected SELECT"),
        }
    }

    #[test]
    fn select_columns() {
        let stmts = parse("SELECT a, b, c FROM users");
        match &stmts[0] {
            Stmt::Select(s) => {
                assert!(!s.all);
                assert_eq!(s.columns, vec!["a", "b", "c"]);
                assert_eq!(s.from, "users");
            }
            _ => panic!("expected SELECT"),
        }
    }

    #[test]
    fn select_with_where() {
        let stmts = parse("SELECT name FROM users WHERE id = 42");
        match &stmts[0] {
            Stmt::Select(s) => {
                assert_eq!(s.from, "users");
                let wc = s.where_clause.as_ref().unwrap();
                assert_eq!(
                    *wc,
                    WhereExpr::Cmp {
                        op: WhereOp::Eq,
                        column: "id".to_string(),
                        value: Value::Integer(42),
                    }
                );
            }
            _ => panic!("expected SELECT"),
        }
    }

    #[test]
    fn select_where_string_value() {
        let stmts = parse("SELECT * FROM users WHERE name = 'alice'");
        match &stmts[0] {
            Stmt::Select(s) => {
                let wc = s.where_clause.as_ref().unwrap();
                assert_eq!(
                    *wc,
                    WhereExpr::Cmp {
                        op: WhereOp::Eq,
                        column: "name".to_string(),
                        value: Value::String("alice".to_string()),
                    }
                );
            }
            _ => panic!("expected SELECT"),
        }
    }

    #[test]
    fn select_where_gt() {
        let stmts = parse("SELECT * FROM t WHERE x > 1");
        match &stmts[0] {
            Stmt::Select(s) => {
                let wc = s.where_clause.as_ref().unwrap();
                assert_eq!(
                    *wc,
                    WhereExpr::Cmp {
                        op: WhereOp::Gt,
                        column: "x".to_string(),
                        value: Value::Integer(1),
                    }
                );
            }
            _ => panic!("expected SELECT"),
        }
    }

    #[test]
    fn select_where_le_ne() {
        let stmts = parse("SELECT * FROM t WHERE y <= 10 AND z <> 0");
        match &stmts[0] {
            Stmt::Select(s) => {
                let wc = s.where_clause.as_ref().unwrap();
                let expected = WhereExpr::And(
                    Box::new(WhereExpr::Cmp {
                        op: WhereOp::Le,
                        column: "y".to_string(),
                        value: Value::Integer(10),
                    }),
                    Box::new(WhereExpr::Cmp {
                        op: WhereOp::Ne,
                        column: "z".to_string(),
                        value: Value::Integer(0),
                    }),
                );
                assert_eq!(*wc, expected);
            }
            _ => panic!("expected SELECT"),
        }
    }

    #[test]
    fn select_where_or() {
        let stmts = parse("SELECT * FROM t WHERE a = 1 OR b = 2");
        match &stmts[0] {
            Stmt::Select(s) => {
                let wc = s.where_clause.as_ref().unwrap();
                let expected = WhereExpr::Or(
                    Box::new(WhereExpr::Cmp {
                        op: WhereOp::Eq,
                        column: "a".to_string(),
                        value: Value::Integer(1),
                    }),
                    Box::new(WhereExpr::Cmp {
                        op: WhereOp::Eq,
                        column: "b".to_string(),
                        value: Value::Integer(2),
                    }),
                );
                assert_eq!(*wc, expected);
            }
            _ => panic!("expected SELECT"),
        }
    }

    #[test]
    fn insert_basic() {
        let stmts = parse("INSERT INTO t VALUES (1, 'hi', 3.14)");
        match &stmts[0] {
            Stmt::Insert(i) => {
                assert_eq!(i.table, "t");
                assert_eq!(
                    i.values,
                    vec![
                        Value::Integer(1),
                        Value::String("hi".to_string()),
                        Value::Real(3.14),
                    ]
                );
            }
            _ => panic!("expected INSERT"),
        }
    }

    #[test]
    fn create_table() {
        let stmts = parse("CREATE TABLE users (id INTEGER, name TEXT, age INTEGER)");
        match &stmts[0] {
            Stmt::CreateTable(ct) => {
                assert_eq!(ct.table, "users");
                assert_eq!(ct.columns.len(), 3);
                assert_eq!(ct.columns[0].name, "id");
                assert_eq!(ct.columns[0].type_name, "INTEGER");
                assert_eq!(ct.columns[1].name, "name");
                assert_eq!(ct.columns[1].type_name, "TEXT");
            }
            _ => panic!("expected CREATE TABLE"),
        }
    }

    #[test]
    fn drop_table() {
        let stmts = parse("DROP TABLE users");
        match &stmts[0] {
            Stmt::DropTable(d) => assert_eq!(d.table, "users"),
            _ => panic!("expected DROP TABLE"),
        }
    }

    #[test]
    fn multiple_statements() {
        let stmts = parse("SELECT * FROM a; SELECT * FROM b;");
        assert_eq!(stmts.len(), 2);
    }

    #[test]
    fn select_with_null_in_where() {
        let stmts = parse("SELECT * FROM t WHERE x = NULL");
        match &stmts[0] {
            Stmt::Select(s) => {
                let wc = s.where_clause.as_ref().unwrap();
                assert_eq!(
                    *wc,
                    WhereExpr::Cmp {
                        op: WhereOp::Eq,
                        column: "x".to_string(),
                        value: Value::Null,
                    }
                );
            }
            _ => panic!("expected SELECT"),
        }
    }
}
